name: 'Run test on Autify for Web'
description: 'Run a test scenario or test plan on Autify for Web.'
author: 'Autify Inc.'
inputs:
  access-token:
    required: true
    description: 'Access token of Autify for Web.'
  autify-test-url:
    required: true
    description: 'URL of a test scenario or test plan e.g. https://app.autify.com/projects/<ID>/(scenarios|test_plans)/<ID>'
  wait:
    required: false
    default: 'false'
    description: 'When true, the action waits until the test finishes.'
  timeout:
    required: false
    description: 'Timeout seconds when waiting.'
  url-replacements:
    required: false
    description: 'URL replacements e.g. http://example.com=http://example.net,http://example.org=http://example.net'
  max-retry-count:
    required: false
    description: 'Maximum retry count while waiting. The command can take up to `timeout * (max-retry-count + 1)`. Only effective with `wait`'
  test-execution-name:
    required: false
    description: 'Name of the test execution (not supported by test plan executions)'
  browser:
    required: false
    description: 'Browser for running the test scenario (not supported by test plan executions)'
  device:
    required: false
    description: 'Device for running the test scenario (not supported by test plan executions)'
  device-type:
    required: false
    description: 'Device type for running the test scenario (not supported by test plan executions)'
  os:
    required: false
    description: 'OS for running the test scenario (not supported by test plan executions)'
  os-version:
    required: false
    description: 'OS version for running the test scenario (not supported by test plan executions)'
  autify-connect:
    required: false
    description: 'Name of the Autify Connect Access Point (not supported by test plan executions)'
  autify-connect-client:
    required: false
    description: 'When true, start Autify Connect Client. (not supported by test plan executions)'
    default: 'false'
  autify-path:
    required: false
    default: 'autify'
    description: 'A path to `autify` which will be used to invoke Autify CLI internally. Default is searching from PATH.'
  autify-cli-installer-url:
    required: false
    default: "https://autify-cli-assets.s3.amazonaws.com/autify-cli/channels/stable/install-cicd.bash"
    description: 'Autify CLI installer URL'

outputs:
  exit-code:
    description: 'Exit code of autify-cli. 0 means succeeded.'
    value: ${{ steps.run.outputs.exit-code }}
  log:
    description: 'Log of stdout and stderr.'
    value: ${{ steps.run.outputs.log }}
  result-url:
    description: 'Test result URL on Autify for Web'
    value: ${{ steps.run.outputs.result-url }}

runs:
  using: 'composite'
  steps:
    - uses: autifyhq/actions-setup-cli@v2
      with:
        shell-installer-url: ${{ inputs.autify-cli-installer-url }}
    - if: ${{ inputs.autify-connect-client == 'true' }}
      run: autify connect client install
      shell: bash
    - id: run
      run: $GITHUB_ACTION_PATH/script.bash
      shell: bash
      env:
        INPUT_ACCESS_TOKEN: ${{ inputs.access-token }}
        INPUT_AUTIFY_TEST_URL: ${{ inputs.autify-test-url }}
        INPUT_WAIT: ${{ inputs.wait }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
        INPUT_URL_REPLACEMENTS: ${{ inputs.url-replacements }}
        INPUT_MAX_RETRY_COUNT: ${{ inputs.max-retry-count }}
        INPUT_TEST_EXECUTION_NAME: ${{ inputs.test-execution-name }}
        INPUT_BROWSER: ${{ inputs.browser }}
        INPUT_DEVICE: ${{ inputs.device }}
        INPUT_DEVICE_TYPE: ${{ inputs.device-type }}
        INPUT_OS: ${{ inputs.os }}
        INPUT_OS_VERSION: ${{ inputs.os-version }}
        INPUT_AUTIFY_CONNECT: ${{ inputs.autify-connect }}
        INPUT_AUTIFY_CONNECT_CLIENT: ${{ inputs.autify-connect-client }}
        INPUT_AUTIFY_PATH: ${{ inputs.autify-path }}
